<?php

/**
 * Implements hook_cron().
 */
function fashion_subscribe_cron() {
    $items = [];
//    $items['fashion_subscribed_users'] = [];



    $stateData = \Drupal::state()->get('users');

    $allDataFromConfig = \Drupal::configFactory()->getEditable('fashion_subscribe.settings')->get();

    $items = array_merge($stateData,$allDataFromConfig);
//    $itemsResult = array_unique($items);
    $a=1;
//    $result = array_map(function($stateData, $allDataFromConfig){
//        return array_merge(isset(($stateData) ? ($stateData : array(), isset($allDataFromConfig) ? $allDataFromConfig : array());
//    },$stateData, $allDataFromConfig);

}